# Generated by Django 2.0.1 on 2018-04-22 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import school.models.auth
import school.models.student


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ClassModel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('first_login', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', school.models.auth.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=school.models.student.upload_location_enquiry)),
                ('date_of_birth', models.DateField()),
                ('aadhar_number', models.IntegerField(null=True)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('current_address', models.CharField(max_length=500, null=True)),
                ('current_qualification', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ClassSessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='FeeCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recipet_no_prefix', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateField(null=True)),
                ('amount_paid', models.IntegerField(null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('fee_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FeeBatch')),
                ('fee_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FeeCategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='FeeSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('fee_type', models.CharField(max_length=30)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FeeCategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='FeeSubCategoryFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.IntegerField()),
                ('fine_type', models.CharField(max_length=30)),
                ('fine_increment', models.CharField(max_length=30)),
                ('fee_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FeeCategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('router_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=school.models.student.upload_location_registration)),
                ('date_of_birth', models.DateField()),
                ('aadhar_number', models.IntegerField(null=True)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('current_address', models.CharField(max_length=500, null=True)),
                ('current_qualification', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('registration_fee', models.IntegerField(null=True)),
                ('apply_for', models.CharField(max_length=100)),
                ('is_shortlisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('permission', models.ManyToManyField(to='school.PermissionModel')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.MainMenu')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_image', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.BigIntegerField()),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(through='school.ClassSessionModel', to='school.ClassModel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('phone_no_1', models.BigIntegerField()),
                ('phone_no_2', models.BigIntegerField()),
                ('perm_address', models.CharField(max_length=500)),
                ('temp_address', models.CharField(max_length=500)),
                ('date_of_hiring', models.DateField()),
                ('higest_education', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=school.models.student.upload_location_student)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
                ('mother_tongue', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('religion', models.CharField(max_length=30, null=True)),
                ('caste', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('pin', models.BigIntegerField(null=True)),
                ('aadhar_number', models.IntegerField(null=True)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('father_phone_no', models.BigIntegerField(null=True)),
                ('mother_phone_no', models.BigIntegerField(null=True)),
                ('father_aadhar', models.BigIntegerField(null=True)),
                ('mother_aadhar', models.BigIntegerField(null=True)),
                ('perm_address', models.CharField(max_length=500)),
                ('temp_address', models.CharField(max_length=500, null=True)),
                ('father_profession', models.CharField(max_length=50)),
                ('mother_profession', models.CharField(max_length=50)),
                ('father_office_address', models.CharField(max_length=500, null=True)),
                ('mother_office_address', models.CharField(max_length=500, null=True)),
                ('pervious_school_name', models.CharField(max_length=200, null=True)),
                ('pervious_school_address', models.CharField(max_length=500, null=True)),
                ('pervious_qualification', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ClassSessionModel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StudentModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMarkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.ExamModel')),
                ('students', models.ManyToManyField(through='school.StudentMarksModel', to='school.StudentSessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.ClassSessionModel')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.SubjectModel')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.StaffModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTimingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True)),
                ('day', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=4)),
                ('subject_session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school.SubjectSessionModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('router_link', models.CharField(max_length=30)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.MainMenu')),
            ],
        ),
        migrations.AddField(
            model_name='subjectmarkmodel',
            name='subject_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SubjectSessionModel'),
        ),
        migrations.AddField(
            model_name='studentmarksmodel',
            name='student_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.StudentSessionModel'),
        ),
        migrations.AddField(
            model_name='studentmarksmodel',
            name='subject_marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.SubjectMarkModel'),
        ),
        migrations.AddField(
            model_name='studentattendencemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StudentSessionModel'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolmodel',
            unique_together={('name', 'code')},
        ),
        migrations.AddField(
            model_name='schoolmenu',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AddField(
            model_name='feesubcategory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SessionModel'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='fine_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.FeeSubCategoryFine'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StudentModel'),
        ),
        migrations.AddField(
            model_name='feecategorymodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AddField(
            model_name='feebatch',
            name='fee_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FeeCategoryModel'),
        ),
        migrations.AddField(
            model_name='feebatch',
            name='fine_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.FeeSubCategoryFine'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AddField(
            model_name='enquirymodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(to='school.RoleModel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AddField(
            model_name='classsessionmodel',
            name='incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StaffModel'),
        ),
        migrations.AddField(
            model_name='classsessionmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SessionModel'),
        ),
        migrations.AddField(
            model_name='classsessionmodel',
            name='students',
            field=models.ManyToManyField(through='school.StudentSessionModel', to='school.StudentModel'),
        ),
        migrations.AddField(
            model_name='classsessionmodel',
            name='subjects',
            field=models.ManyToManyField(through='school.SubjectSessionModel', to='school.SubjectModel'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolModel'),
        ),
        migrations.AlterUniqueTogether(
            name='subjecttimingmodel',
            unique_together={('subject_session', 'time', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectsessionmodel',
            unique_together={('subject', 'class_session', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectmodel',
            unique_together={('code', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectmarkmodel',
            unique_together={('exam', 'subject_session', 'max_marks')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsessionmodel',
            unique_together={('student', 'class_session')},
        ),
        migrations.AlterUniqueTogether(
            name='studentmarksmodel',
            unique_together={('student_session', 'subject_marks', 'marks')},
        ),
        migrations.AlterUniqueTogether(
            name='studentattendencemodel',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionmodel',
            unique_together={('start_date', 'end_date', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='exammodel',
            unique_together={('name', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='classsessionmodel',
            unique_together={('class_id', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='classmodel',
            unique_together={('name', 'section', 'school')},
        ),
    ]
